
# Gem::Specification for Cap_gun-0.0.3
# Originally generated by Echoe

Gem::Specification.new do |s|
  s.name = %q{cap_gun}
  s.version = "0.0.3"

  s.specification_version = 2 if s.respond_to? :specification_version=

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Rob Sanheim, Relevance"]
  s.date = %q{2008-06-17}
  s.description = %q{Super simple capistrano deployments.}
  s.email = %q{opensource@thinkrelevance.com}
  s.extra_rdoc_files = ["CHANGELOG", "lib/cap_gun.rb", "MIT-LICENSE", "README.rdoc"]
  s.files = ["CHANGELOG", "init.rb", "install.rb", "lib/cap_gun.rb", "manifest.txt", "MIT-LICENSE", "README.rdoc", "spec/cap_gun_spec.rb", "tasks/cap_bot_tasks.rake", "vendor/action_mailer_tls/init.rb", "vendor/action_mailer_tls/lib/smtp_tls.rb", "vendor/action_mailer_tls/README", "vendor/action_mailer_tls/sample/mailer.yml.sample", "vendor/action_mailer_tls/sample/smtp_gmail.rb", "cap_gun.gemspec"]
  s.has_rdoc = true
  s.homepage = %q{http://opensource.thinkrelevance.com/wiki/cap_gun}
  s.rdoc_options = ["--line-numbers", "--inline-source", "--title", "Cap_gun", "--main", "README.rdoc"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{thinkrelevance}
  s.rubygems_version = %q{1.1.1}
  s.summary = %q{Bang! You're deployed!}
  s.test_files = ["spec/cap_gun_spec.rb"]
end


# # Original Rakefile source (requires the Echoe gem):
# 
# require 'rubygems'
# require 'echoe'
# require './lib/cap_gun.rb'
# 
# hoe = Echoe.new('cap_gun') do |p|
#   p.rubyforge_name = 'thinkrelevance'
#   p.author = ["Rob Sanheim", "Relevance"]
#   p.email = 'opensource@thinkrelevance.com'
#   p.version = CapGun::VERSION
#   p.summary = "Bang! You're deployed!"
#   p.description = 'Super simple capistrano deployments.'
#   p.url = "http://opensource.thinkrelevance.com/wiki/cap_gun"
#   p.rdoc_pattern = /^(lib|bin|ext)|txt|rdoc|CHANGELOG|MIT-LICENSE$/
#   rdoc_template = `allison --path`.strip << ".rb"
#   p.rdoc_template = rdoc_template
#   p.test_pattern = 'spec/**/*_spec.rb'
#   p.manifest_name = 'manifest.txt'
# end