
# Gem::Specification for Cap_gun-0.0.8.1
# Originally generated by Echoe

--- !ruby/object:Gem::Specification 
name: cap_gun
version: !ruby/object:Gem::Version 
  version: 0.0.8.1
platform: ruby
authors: 
- Rob Sanheim, Relevance
autorequire: 
bindir: bin

date: 2008-10-03 00:00:00 -04:00
default_executable: 
dependencies: 
- !ruby/object:Gem::Dependency 
  name: echoe
  type: :development
  version_requirement: 
  version_requirements: !ruby/object:Gem::Requirement 
    requirements: 
    - - ">="
      - !ruby/object:Gem::Version 
        version: "0"
    version: 
description: Super simple capistrano deployments.
email: opensource@thinkrelevance.com
executables: []

extensions: []

extra_rdoc_files: 
- CHANGELOG
- lib/cap_gun.rb
- MIT-LICENSE
- README.rdoc
files: 
- cap_gun.gemspec
- CHANGELOG
- init.rb
- install.rb
- lib/cap_gun.rb
- manifest.txt
- MIT-LICENSE
- Rakefile
- README.rdoc
- spec/cap_gun_spec.rb
- tasks/cap_bot_tasks.rake
- vendor/action_mailer_tls/init.rb
- vendor/action_mailer_tls/lib/smtp_tls.rb
- vendor/action_mailer_tls/README
- vendor/action_mailer_tls/sample/mailer.yml.sample
- vendor/action_mailer_tls/sample/smtp_gmail.rb
has_rdoc: true
homepage: http://opensource.thinkrelevance.com/wiki/cap_gun
post_install_message: 
rdoc_options: 
- --line-numbers
- --inline-source
- --title
- Cap_gun
- --main
- README.rdoc
require_paths: 
- lib
required_ruby_version: !ruby/object:Gem::Requirement 
  requirements: 
  - - ">="
    - !ruby/object:Gem::Version 
      version: "0"
  version: 
required_rubygems_version: !ruby/object:Gem::Requirement 
  requirements: 
  - - ">="
    - !ruby/object:Gem::Version 
      version: "1.2"
  version: 
requirements: []

rubyforge_project: thinkrelevance
rubygems_version: 1.3.0
specification_version: 2
summary: Bang! You're deployed!
test_files: 
- spec/cap_gun_spec.rb
